### ISSUE TITLE
Consider splitting out heavyweight extras as other outputs

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/sklearn-genetic-opt-feedstock#1]
## References

- https://github.com/conda-forge/staged-recipes/issues/24079

## Problem

Upstream, it appears [tensorflow](https://github.com/rodrigo-arenas/Sklearn-genetic-opt/blob/0.10.1/setup.py#L50) is an optional dependency.

As there is currently no compatible `tensorflow 2.x` for some platforms such as `win-64` on conda-forge, this package is not installable.

## Alternatives

While the `tensorflow` dependency _could_ just be removed, as it _does_ have a bottom pin, it might be worthwhile to at least make these `run_constrained` dependencies instead of `run` dependencies.

A more complex approach would be to break up the dependencies into multiple [outputs](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#outputs-section), such that in its final state, the recipe might build:

```yaml
outputs:
  - name: sklearn-genetic-opt
  # which is depended upon by...
  - name: sklearn-genetic-opt-with-mflow
  - name: sklearn-genetic-opt-with-seaborn
  - name: sklearn-genetic-opt-with-tensorflow
  # which can _all_ be installed with...
  - name: sklearn-genetic-opt-with-all
```
